#1 На главной странице указать имя и фамилию разработчика
oshatrk-master/cm-test pull request #10
Opened 2017-02-26 12:18 UTC by oshatrk

This PR will close #1 on merge.

PR для работы над Issue #1:
1. На главной странице указать имя и фамилию разработчика.

2017-02-26 12:30 UTC, oshatrk commented
Это же просто!
@oshatrk-master, проверь 1d832d5, и в продакшн ;)

2017-02-26 12:39 UTC, oshatrk-master requested changes
Что-то слишком просто )
Если пользователь будет не из России, то у него может не быть шрифта с кириллицей. 
Нужно локализовать хотя бы для английской локали.

Кроме того, поскольку это обязательное требование задачи, то стоит написать приемочный тест.

Кстати, в конце файла автоматом добавилась пустая строка — это из-за стиля `insert_final_newline = true` в файле `/.editorconfig`. Стоит привести стилевое оформление проекта к какому-нибудь единому стандарту.

2017-03-02 12:29 UTC, oshatrk-master reviewed
Все в порядке. Отмечу, что сделано.

2017-03-02 12:33 UTC, oshatrk-master approved these changes

2017-03-02 12:33 UTC, merged

2017-03-19 17:55 UTC, oshatrk commented
Обнаружено отсутствие пробела перед именем.